"use client";

import { useEffect, useMemo, useState } from "react";

type DemoStage = "CONNECTED" | "TELEMETRY" | "HEALTHY" | "ATTACK_STARTED" | "TRAFFIC_CHANGED" | "ANOMALY_DETECTED" | "TRUST_COLLAPSE" | "CLASSIFIED" | "MITRE_MAPPED" | "FORENSICS" | "AWAITING_REMEDIATION" | "REMEDIATING" | "RECOVERY" | "VERIFYING" | "HEALTHY_AGAIN" | "RESYNC";
type FlowStep = { stage: DemoStage; label: string; detail: string; technology: string; purpose: string };

const flow: FlowStep[] = [
  { stage: "CONNECTED", label: "Connect", detail: "Raspberry Pi / PI-001 connected", technology: "Raspberry Pi · PI-001", purpose: "Physical endpoint identity is registered with the digital twin." },
  { stage: "TELEMETRY", label: "Observe", detail: "Live telemetry begins", technology: "Npcap · TShark · tshark_live.py", purpose: "Capture Windows network traffic and normalize one-second telemetry windows." },
  { stage: "HEALTHY", label: "Baseline", detail: "Trust 98 · State HEALTHY", technology: "FastAPI · Telemetry Window API", purpose: "The observed window matches the learned PI-001 baseline." },
  { stage: "ATTACK_STARTED", label: "Attack", detail: "Controlled SYN attack starts", technology: "VMware Linux VM · Scapy · pi-syn-demo", purpose: "The registered attacker generates SYN packets toward PI-001." },
  { stage: "TRAFFIC_CHANGED", label: "Divergence", detail: "Real packet behavior changes", technology: "Aegis Hybrid Engine", purpose: "Packet rate rises while inter-arrival time and handshake symmetry shift." },
  { stage: "ANOMALY_DETECTED", label: "Detect", detail: "Aegis detects divergence", technology: "LSTM-VAE · Jensen-Shannon Divergence", purpose: "Temporal behavior and traffic distributions no longer resemble normal." },
  { stage: "TRUST_COLLAPSE", label: "Decide", detail: "HEALTHY → SUSPICIOUS → ATTACK", technology: "Aegis Trust Composer", purpose: "Temporal anomaly, distribution drift, and known evidence combine into operational risk." },
  { stage: "CLASSIFIED", label: "Classify", detail: "Known attack classified", technology: "XGBoost · YAML Security Rules", purpose: "The known SYN FLOOD signature is matched with high confidence." },
  { stage: "MITRE_MAPPED", label: "Map", detail: "MITRE T1498.001", technology: "MITRE ATT&CK", purpose: "Direct Network Flood is attached to the incident evidence." },
  { stage: "FORENSICS", label: "Prove", detail: "Forensic report created", technology: "Forensic Report Pipeline", purpose: "Incident evidence, scores, windows, and timeline are captured." },
  { stage: "AWAITING_REMEDIATION", label: "Review", detail: "Operator action required", technology: "Human-in-the-loop", purpose: "The demo pauses so the operator can authorize containment." },
  { stage: "REMEDIATING", label: "Contain", detail: "Registered attack job stopped", technology: "Allowlisted Remediation Controller", purpose: "The frontend represents isolation or the guaranteed pi-syn-demo fallback." },
  { stage: "RECOVERY", label: "Recover", detail: "Pi traffic returns to baseline", technology: "Trust / State Engine", purpose: "Traffic gradually settles and the device enters RECOVERING." },
  { stage: "VERIFYING", label: "Verify", detail: "Clean windows verified", technology: "FastAPI · SSE", purpose: "Multiple clean telemetry windows confirm recovery." },
  { stage: "HEALTHY_AGAIN", label: "Restore", detail: "Trust 97 · State HEALTHY", technology: "Aegis Trust Composer", purpose: "Trust returns above 95 only after clean-window verification." },
  { stage: "RESYNC", label: "Re-sync", detail: "Digital twin synchronized", technology: "Aegis Digital Twin", purpose: "Physical and digital state agree again." }
];
const stageIndex = (stage: DemoStage) => flow.findIndex((item) => item.stage === stage);
function stageData(stage: DemoStage, progress: number) {
  const attack = stageIndex(stage) >= stageIndex("ATTACK_STARTED") && stageIndex(stage) < stageIndex("REMEDIATING");
  const recovering = stageIndex(stage) >= stageIndex("RECOVERY");
  const trust = stage === "TRUST_COLLAPSE" ? Math.round(98 - progress * 80) : attack ? 18 : recovering ? Math.round(18 + Math.min(79, progress * 79)) : 98;
  return { attack, recovering, trust: Math.max(18, Math.min(98, trust)), anomaly: attack ? (stage === "TRUST_COLLAPSE" ? Math.min(.94, .2 + progress * .74) : .94) : recovering ? Math.max(.03, .94 - progress * .91) : .02, jsd: attack ? (recovering ? Math.max(.02, .71 - progress * .69) : .71) : .01, packetRate: attack ? 1842 : recovering ? Math.round(1842 - Math.min(1830, progress * 1830)) : 12 };
}

function Metrics({ stage, progress }: { stage: DemoStage; progress: number }) { const metrics = stageData(stage, progress); return <aside className="xai-metrics"><div className="xai-metric-heading"><span className="eyebrow">Live metrics</span><small>DEMO MODE · PI-001</small></div><div className="xai-metric"><span>Trust</span><strong className={metrics.attack ? "metric-danger" : ""}>{metrics.trust}<small>/100</small></strong></div><div className="xai-metric"><span>State</span><strong className={`state-text ${metrics.attack ? "metric-danger" : metrics.recovering ? "metric-warning" : "metric-success"}`}>{stage === "AWAITING_REMEDIATION" ? "ATTACK" : metrics.recovering && stage !== "HEALTHY_AGAIN" && stage !== "RESYNC" ? "RECOVERING" : metrics.attack ? "ATTACK" : "HEALTHY"}</strong></div><div className="xai-metric-grid"><div><span>Packet rate</span><b>{metrics.packetRate}<small>/s</small></b></div><div><span>Anomaly</span><b>{metrics.anomaly.toFixed(2)}</b></div><div><span>JSD</span><b>{metrics.jsd.toFixed(2)}</b></div><div><span>Window</span><b>1 sec</b></div></div></aside>; }

function Architecture({ stage, progress }: { stage: DemoStage; progress: number }) { const metrics = stageData(stage, progress); return <div className="xai-architecture"><div className="xai-attacker"><span className="xai-node-kicker">CONTROLLED ATTACKER</span><strong>VMware Linux VM</strong><small>Scapy · pi-syn-demo</small><i className={metrics.attack ? "traffic-active" : ""}>SYN</i></div><div className="xai-path"><div className="xai-node node-pi"><span>01</span><strong>Raspberry Pi</strong><b>PI-001</b><small>Physical endpoint</small></div><div className="xai-connector"><i className={metrics.attack ? "packet-burst" : "packet-normal"} /></div><div className="xai-node"><span>02</span><strong>Capture layer</strong><b>Npcap + TShark</b><small>tshark_live.py</small></div><div className="xai-connector"><i className={metrics.attack ? "packet-burst" : "packet-normal"} /></div><div className="xai-node node-engine"><span>03</span><strong>Aegis engine</strong><b>FastAPI · Hybrid detection</b><small>LSTM-VAE · JSD · YAML rules</small></div><div className="xai-connector"><i className={metrics.attack ? "packet-burst" : "packet-normal"} /></div><div className="xai-node"><span>04</span><strong>Decision layer</strong><b>XGBoost · MITRE</b><small>Forensics + remediation</small></div></div></div>; }

function DetectionEvidence({ stage, progress }: { stage: DemoStage; progress: number }) { const metrics = stageData(stage, progress); const detection = stageIndex(stage) >= stageIndex("ANOMALY_DETECTED"); return <section className="xai-evidence"><div className="xai-section-heading"><div><span className="eyebrow">Behind the detection</span><h3>Evidence and calculations</h3></div><span className={detection ? "evidence-live" : "evidence-idle"}>{detection ? "ANALYSIS ACTIVE" : "BASELINE MONITORING"}</span></div><div className="xai-calculation-grid"><div className="calculation-card"><span className="calculation-label">TRAFFIC WINDOW</span><div className="comparison"><div><small>Baseline</small><b>68 B</b><b>420 ms</b><b>.54</b><b>.91</b></div><div className="comparison-arrow">→</div><div className={detection ? "observed-alert" : ""}><small>Observed</small><b>{metrics.attack ? "142 B" : "68 B"}</b><b>{metrics.attack ? "21 ms" : "420 ms"}</b><b>{metrics.attack ? ".81" : ".54"}</b><b>{metrics.attack ? ".42" : ".91"}</b></div></div><small className="calculation-foot">Packet size · inter-arrival · entropy · symmetry</small></div><div className="calculation-card"><span className="calculation-label">DEVIATION MODEL</span><p>| observed − baseline | / baseline</p><div className="deviation-list"><span>Δ packet size <b className={detection ? "value-alert" : ""}>{metrics.attack ? "+108%" : "+0%"}</b></span><span>Δ inter-arrival <b className={detection ? "value-alert" : ""}>{metrics.attack ? "−95%" : "−0%"}</b></span><span>Jensen-Shannon Divergence <b>{metrics.jsd.toFixed(2)}</b></span><span>Temporal anomaly <b>{metrics.anomaly.toFixed(2)}</b></span></div></div><div className="calculation-card decision-card"><span className="calculation-label">TRUST COMPOSER</span><div className="signal-row"><span>LSTM-VAE</span><b>{metrics.anomaly.toFixed(2)}</b></div><div className="signal-row"><span>JSD drift</span><b>{metrics.jsd.toFixed(2)}</b></div><div className="signal-row"><span>YAML signature</span><b>{detection ? "MATCH" : "LOW"}</b></div><div className="trust-result"><span>Operational trust</span><strong>{metrics.trust}<small>/100</small></strong></div></div></div></section>; }

function TechnologyPanel({ current }: { current: FlowStep }) { return <section className="xai-tech"><span className="eyebrow">Active technology</span><h3>{current.technology}</h3><p>{current.purpose}</p><div className="xai-tech-output"><span>STAGE OUTPUT</span><b>{current.detail}</b></div></section>; }

export function AttackLifecycleDemo() { const [stage, setStage] = useState<DemoStage>("CONNECTED"); const [progress, setProgress] = useState(0); const [running, setRunning] = useState(false); const current = flow.find((item) => item.stage === stage) ?? flow[0]; const canAdvance = stage !== "AWAITING_REMEDIATION" && stage !== "RESYNC"; const reset = () => { setStage("CONNECTED"); setProgress(0); setRunning(false); };
  useEffect(() => { if (!running || !canAdvance) return; const timer = window.setInterval(() => { setProgress((value) => { if (value < 1) return Math.min(1, value + .08); const next = flow[stageIndex(stage) + 1]; if (next) setStage(next.stage); return 0; }); }, 260); return () => window.clearInterval(timer); }, [running, stage, canAdvance]);
  const start = () => { if (stage === "RESYNC") reset(); setRunning(true); }; const remediate = () => { if (stage === "AWAITING_REMEDIATION") { setStage("REMEDIATING"); setProgress(0); setRunning(true); } }; const status = useMemo(() => stage === "RESYNC" ? "DIGITAL TWIN RE-SYNCHRONIZED" : current.detail, [stage, current.detail]);
  return <section className="xai-demo"><div className="xai-demo-header"><div><span className="eyebrow">Explainable AI lab · deterministic simulation</span><h2>Live attack lifecycle</h2><p>Watch what physically changes at PI-001 and how Aegis reasons from the evidence.</p></div><div className="xai-actions"><span className={`xai-demo-status ${stage === "AWAITING_REMEDIATION" ? "status-warning" : ""}`}><i />{status}</span>{stage === "AWAITING_REMEDIATION" ? <button className="xai-contain" onClick={remediate}>CONTAIN &amp; REMEDIATE</button> : <button className="xai-run" onClick={start}>{stage === "RESYNC" ? "REPLAY DEMONSTRATION" : running ? "DEMONSTRATION RUNNING" : "RUN DEMONSTRATION"}</button>}</div></div><div className="xai-timeline">{flow.map((item, index) => <div className={`timeline-step ${index < stageIndex(stage) ? "complete" : ""} ${item.stage === stage ? "current" : ""}`} key={item.stage}><span>{index < stageIndex(stage) ? "✓" : String(index + 1).padStart(2, "0")}</span><small>{item.label}</small></div>)}</div><div className="xai-main-grid"><Architecture stage={stage} progress={progress} /><Metrics stage={stage} progress={progress} /></div><div className="xai-detail-grid"><DetectionEvidence stage={stage} progress={progress} /><TechnologyPanel current={current} /></div><div className="xai-incident-strip"><span className="eyebrow">Scenario</span><strong>PI-001 + VMware Linux VM + SYN FLOOD</strong><span>{stageIndex(stage) >= stageIndex("CLASSIFIED") ? "MITRE ATT&CK T1498.001 · Direct Network Flood" : "Known attack evidence will appear after detection"}</span></div></section>;
}