"use client";

import { useState } from "react";
import { aegisCapabilities, architectureNodes, tierDescriptions, type ArchitectureNode } from "@/lib/industrialArchitecture";

const tierNodes = (tier: ArchitectureNode["tier"]) => architectureNodes.filter((node) => node.tier === tier);

function ArchitectureNodeCard({ node, selected, onSelect }: { node: ArchitectureNode; selected: boolean; onSelect: () => void }) {
  return <button type="button" className={`architecture-node architecture-${node.tone ?? "system"} ${selected ? "architecture-selected" : ""}`} onClick={onSelect} aria-expanded={selected}><span className="architecture-node-id">{node.tone === "security" ? "BOUNDARY" : node.tone === "aegis" ? "OUR SECURITY LAYER" : "SYSTEM"}</span><strong>{node.name}</strong><small>{node.subtitle}</small>{node.tone === "aegis" && <span className="architecture-capability-line">BASELINE · DETECT · TRUST · RECOVER</span>}</button>;
}

function Tier({ id, label, title, subtitle, selected, onSelect }: { id: ArchitectureNode["tier"]; label: string; title: string; subtitle: string; selected: string; onSelect: (node: ArchitectureNode) => void }) {
  return <section className={`architecture-tier tier-${id}`}><div className="tier-heading"><div><span className="eyebrow">{label}</span><h3>{title}</h3><p>{subtitle}</p></div><span className="tier-description">{tierDescriptions[id]}</span></div><div className="tier-node-grid">{tierNodes(id).map((node) => <ArchitectureNodeCard key={node.id} node={node} selected={node.id === selected} onSelect={() => onSelect(node)} />)}</div></section>;
}

export function IndustrialArchitecture() {
  const [selected, setSelected] = useState<ArchitectureNode>(architectureNodes.find((node) => node.id === "aegis") ?? architectureNodes[0]);
  return <section className="industrial-architecture"><div className="architecture-header"><div><span className="eyebrow">System architecture · conceptual deployment model</span><h2>Where Aegis-Twin fits</h2><p>A device-level security and trust layer inside the industrial cybersecurity ecosystem.</p></div><span className="source-badge">ARCHITECTURE OVERVIEW</span></div><div className="architecture-message">Aegis-Twin works alongside firewalls, SIEM, SOC, XDR/EDR, IDS/IPS, and IAM to continuously assess IoT and OT behavior and verify recovery after an incident.</div><div className="architecture-flow-label">EXTERNAL CONNECTIVITY <span>↓</span> CONTROLLED APPLICATION ZONE <span>↓</span> INDUSTRIAL NETWORK</div><div className="architecture-diagram"><div className="firewall-boundary"><span>FIREWALL 1 · PERIMETER FIREWALL</span><small>Protects enterprise infrastructure from external threats</small></div><Tier id="enterprise" label="TIER 3" title="Enterprise / IT" subtitle="Corporate systems, users, cloud services, and security operations" selected={selected.id} onSelect={setSelected} /><div className="firewall-boundary"><span>FIREWALL 2 · DMZ FIREWALL</span><small>Controls enterprise-to-application traffic</small></div><Tier id="dmz" label="TIER 2" title="DMZ / Application" subtitle="Controlled zone for application and remote-access services" selected={selected.id} onSelect={setSelected} /><div className="firewall-boundary firewall-ot"><span>FIREWALL 3 · OT FIREWALL</span><small>Protects industrial and IoT networks from unauthorized traffic</small></div><Tier id="ot" label="TIER 1" title="Industrial / OT" subtitle="Industrial control systems and IoT devices" selected={selected.id} onSelect={setSelected} /></div><div className="architecture-detail"><div><span className="eyebrow">Selected component</span><h3>{selected.name}</h3><p>{selected.role}</p></div>{selected.id === "aegis" && <div className="aegis-capabilities">{aegisCapabilities.map((capability) => <span key={capability}>{capability}</span>)}</div>}<div className="architecture-detail-note"><strong>Aegis complements the security stack.</strong><span>Telemetry and detections can flow to SIEM and SOC; remediation remains controlled and allowlisted.</span></div></div><div className="architecture-explanations"><div><b>ENTERPRISE / IT</b><span>{tierDescriptions.enterprise}</span></div><div><b>DMZ / APPLICATION</b><span>{tierDescriptions.dmz}</span></div><div><b>INDUSTRIAL / OT</b><span>{tierDescriptions.ot}</span></div></div><div className="architecture-final"><span>DEVICE BEHAVIOR → DETECTION → TRUST ASSESSMENT → RESPONSE → RECOVERY VERIFICATION</span><strong>Aegis-Twin does not replace the industrial security stack. It adds a device-level trust and recovery layer to it.</strong></div></section>;
}
