import Link from "next/link";

export default function ReportsPage() {
  return (
    <main className="soc-page">
      <header className="topbar">
        <Link href="/dashboard" className="brand"><span className="brand-mark">A</span><span>AEGIS<span>-TWIN</span></span></Link>
        <nav><Link href="/dashboard">Fleet overview</Link><Link className="nav-active" href="/reports">Reports</Link></nav>
        <span className="operator"><i /> SOC / OPERATOR 07</span>
      </header>
      <div className="page-wrap reports-page">
        <div className="page-intro"><div><span className="eyebrow">Security operations center · archive</span><h1>Reports</h1><p>Incident and device security reports generated by fleet activity.</p></div></div>
        <section className="reports-empty panel"><span className="reports-mark">—</span><h2>No reports to show</h2><p>Reports will appear here when an attack or security incident is recorded.</p><Link href="/dashboard">Return to fleet overview</Link></section>
      </div>
    </main>
  );
}